FROM dinotools/dionaea:latest

# Dionaea JSON log module configuration
COPY dionaea.cfg /opt/dionaea/etc/dionaea/dionaea.cfg

ENV DIONAEA_LOG_PATH=/opt/dionaea/var/log

EXPOSE 21 42 69 80 135 443 445 1433 3306 5060 5061
