FROM ubuntu:22.04
RUN apt-get update && apt-get install -y curl xz-utils unzip tar ca-certificates
RUN curl -LO https://github.com/midnightntwrk/compact/releases/download/compact-v0.5.1/compact-x86_64-unknown-linux-musl.tar.xz && tar -xf compact-x86_64-unknown-linux-musl.tar.xz && mv compact-x86_64-unknown-linux-musl/compact /usr/local/bin/
RUN compact update
WORKDIR /app
