/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttackersRouteImport } from './routes/attackers'
import { Route as BlocklistRouteImport } from './routes/blocklist'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HoneypotsRouteImport } from './routes/honeypots'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatLedgerRouteImport } from './routes/threat-ledger'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackersRoute = AttackersRouteImport.update({
  id: '/attackers',
  path: '/attackers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocklistRoute = BlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneypotsRoute = HoneypotsRouteImport.update({
  id: '/honeypots',
  path: '/honeypots',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatLedgerRoute = ThreatLedgerRouteImport.update({
  id: '/threat-ledger',
  path: '/threat-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attackers': typeof AttackersRoute
  '/blocklist': typeof BlocklistRoute
  '/dashboard': typeof DashboardRoute
  '/honeypots': typeof HoneypotsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/threat-ledger': typeof ThreatLedgerRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attackers': typeof AttackersRoute
  '/blocklist': typeof BlocklistRoute
  '/dashboard': typeof DashboardRoute
  '/honeypots': typeof HoneypotsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/threat-ledger': typeof ThreatLedgerRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attackers': typeof AttackersRoute
  '/blocklist': typeof BlocklistRoute
  '/dashboard': typeof DashboardRoute
  '/honeypots': typeof HoneypotsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/threat-ledger': typeof ThreatLedgerRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attackers'
    | '/blocklist'
    | '/dashboard'
    | '/honeypots'
    | '/login'
    | '/settings'
    | '/threat-ledger'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attackers'
    | '/blocklist'
    | '/dashboard'
    | '/honeypots'
    | '/login'
    | '/settings'
    | '/threat-ledger'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/attackers'
    | '/blocklist'
    | '/dashboard'
    | '/honeypots'
    | '/login'
    | '/settings'
    | '/threat-ledger'
    | '/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttackersRoute: typeof AttackersRoute
  BlocklistRoute: typeof BlocklistRoute
  DashboardRoute: typeof DashboardRoute
  HoneypotsRoute: typeof HoneypotsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ThreatLedgerRoute: typeof ThreatLedgerRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attackers': {
      id: '/attackers'
      path: '/attackers'
      fullPath: '/attackers'
      preLoaderRoute: typeof AttackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocklist': {
      id: '/blocklist'
      path: '/blocklist'
      fullPath: '/blocklist'
      preLoaderRoute: typeof BlocklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honeypots': {
      id: '/honeypots'
      path: '/honeypots'
      fullPath: '/honeypots'
      preLoaderRoute: typeof HoneypotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-ledger': {
      id: '/threat-ledger'
      path: '/threat-ledger'
      fullPath: '/threat-ledger'
      preLoaderRoute: typeof ThreatLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttackersRoute: AttackersRoute,
  BlocklistRoute: BlocklistRoute,
  DashboardRoute: DashboardRoute,
  HoneypotsRoute: HoneypotsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ThreatLedgerRoute: ThreatLedgerRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
