/**
 * midnight-bridge — Minimal internal HTTP service wrapping Midnight SDK calls.
 *
 * This is the ONLY component that talks to the Midnight proof server and wallet.
 * The Python backend calls it via normal internal HTTP requests, same pattern
 * already used for the pfSense REST API integration in the response engine.
 *
 * Endpoints:
 *   POST /attest         — submit an attestation (indicatorHash + severityScore)
 *   GET  /query/:hash    — look up corroboration count for an indicator
 *   GET  /stats          — return totalAttestations from ledger state
 *   GET  /health         — health check
 *
 * When MIDNIGHT_SIMULATE=true, all endpoints return realistic mock responses
 * without requiring a running proof server or deployed contract. This is the
 * default for local development.
 */

require("dotenv").config();
const express = require("express");
const cors = require("cors");
const crypto = require("crypto");

const app = express();
app.use(cors());
app.use(express.json());

const PORT = parseInt(process.env.PORT || "3001", 10);
const SIMULATE = (process.env.MIDNIGHT_SIMULATE || "true") === "true";

// ─── In-memory simulation state ─────────────────────────────────────────────
// Used when MIDNIGHT_SIMULATE=true (default for local dev). Mimics the
// on-chain ledger state so the full stack is testable without a proof server.

const simState = {
  corroborationCount: new Map(),    // hash → count
  highConfidenceCount: new Map(),   // hash → count
  totalAttestations: 0,
  transactions: new Map(),          // txHash → { indicatorHash, severityScore, timestamp, status }
};

function simAttest(indicatorHash, severityScore) {
  const current = simState.corroborationCount.get(indicatorHash) || 0;
  simState.corroborationCount.set(indicatorHash, current + 1);
  simState.totalAttestations += 1;

  if (severityScore >= 70) {
    const currentHigh = simState.highConfidenceCount.get(indicatorHash) || 0;
    simState.highConfidenceCount.set(indicatorHash, currentHigh + 1);
  }

  const txHash = "0x" + crypto.randomBytes(32).toString("hex");
  simState.transactions.set(txHash, {
    indicatorHash,
    severityScore,
    timestamp: new Date().toISOString(),
    status: "confirmed",
  });

  return txHash;
}

function simQuery(indicatorHash) {
  return {
    corroborationCount: simState.corroborationCount.get(indicatorHash) || 0,
    highConfidenceCount: simState.highConfidenceCount.get(indicatorHash) || 0,
  };
}

let midnightContract = null;
let midnightProviders = null;

async function initMidnight() {
  if (SIMULATE) return;
  console.log("Initializing real Midnight SDK...");
  try {
    const { httpClientProofProvider } = await import('@midnight-ntwrk/midnight-js-http-client-proof-provider');
    const { indexerPublicDataProvider } = await import('@midnight-ntwrk/midnight-js-indexer-public-data-provider');
    const { NodeZkConfigProvider } = await import('@midnight-ntwrk/midnight-js-node-zk-config-provider');
    const { levelPrivateStateProvider } = await import('@midnight-ntwrk/midnight-js-level-private-state-provider');
    const { WalletBuilder } = await import('@midnight-ntwrk/wallet');
    const { NetworkId } = await import('@midnight-ntwrk/zswap');
    
    // Note: These artifacts must be generated by compactc
    const defenseLedger = await import('../midnight/contract/build/defense_ledger.mjs');
    
    const indexerUrl = process.env.MIDNIGHT_INDEXER_URL || 'http://127.0.0.1:8088/api/v1/graphql';
    const indexerWsUrl = process.env.MIDNIGHT_INDEXER_WS_URL || 'ws://127.0.0.1:8088/api/v1/graphql/ws';
    const proverUrl = process.env.MIDNIGHT_PROOF_SERVER_URL || 'http://127.0.0.1:6300';
    const nodeUrl = process.env.MIDNIGHT_NODE_URL || 'http://127.0.0.1:9944';

    const { createMidnightProvider } = await import('@midnight-ntwrk/midnight-js');
    const { walletProvider } = await import('@midnight-ntwrk/wallet-api');

    const zkConfigProvider = new NodeZkConfigProvider('../midnight/contract/contract');

    midnightProviders = {
      privateStateProvider: levelPrivateStateProvider({
        privateStateStoreName: 'defense-ledger-state',
        privateStoragePasswordProvider: async () => 'password-must-be-16-chars-long',
        accountId: '0000000000000000000000000000000000000000000000000000000000000000'
      }),
      zkConfigProvider: zkConfigProvider,
      publicDataProvider: indexerPublicDataProvider(indexerUrl, indexerWsUrl),
      proofProvider: httpClientProofProvider(proverUrl, zkConfigProvider),
      walletProvider: walletProvider(process.env.MIDNIGHT_WALLET_SEED || '0000000000000000000000000000000000000000000000000000000000000001', proverUrl)
    };
    
    const provider = await createMidnightProvider(midnightProviders);
    midnightProviders.midnightProvider = provider;
    
    if (process.env.MIDNIGHT_CONTRACT_ADDRESS) {
       // Note: in modern SDK, joining might be different, but for now we keep similar semantics
       // midnightContract = await deployContract(...) instead of createMidnightProvider
       // The modern SDK typically uses a generic wrapper, but we'll assume a similar signature for joinContract 
       // if it existed on the contract module itself. Since this is an uncompleted bridge, we will log it.
       console.log("Joined existing contract (logic needs to use contract's createCircuitCallTxInterface):", process.env.MIDNIGHT_CONTRACT_ADDRESS);
    } else {
       console.log("No contract address provided, waiting for /deploy to be called...");
    }
  } catch (err) {
    console.error("Failed to initialize Midnight SDK. Make sure compactc has compiled the contract artifacts into ../midnight/contract/build/.", err.message);
  }
}
initMidnight();

// ─── Routes ─────────────────────────────────────────────────────────────────

app.post("/deploy", async (req, res) => {
  if (SIMULATE) return res.status(400).json({ error: "Cannot deploy in simulate mode" });
  try {
     const { deployContract } = await import('@midnight-ntwrk/midnight-js-contracts');
     const defenseLedger = await import('../midnight/contract/build/defense_ledger.mjs');
     
     if (!midnightProviders) throw new Error("Midnight providers not initialized");

     // The contract requires some initial private state depending on the ledger definitions
     // For defense_ledger, it might not require any complex initialization.
     const initialPrivateState = defenseLedger.initialState ? defenseLedger.initialState({}) : {};
     
     midnightContract = await deployContract(midnightProviders, {
        compiledContract: defenseLedger.contract,
        initialPrivateState: initialPrivateState
     });
     
     return res.json({
        contractAddress: midnightContract.deployTxData.public.contractAddress,
        status: "deployed"
     });
  } catch(err) {
     res.status(500).json({error: "Deploy failed", detail: err.message});
  }
});

/**
 * POST /attest
 * Body: { indicatorHash: string (hex, 64 chars), severityScore: number (0-100) }
 * Response: { txHash: string, status: "confirmed" | "pending" | "failed" }
 */
app.post("/attest", async (req, res) => {
  try {
    const { indicatorHash, severityScore } = req.body;

    if (!indicatorHash || typeof indicatorHash !== "string") {
      return res.status(400).json({ error: "indicatorHash is required and must be a hex string" });
    }
    if (severityScore === undefined || typeof severityScore !== "number" || severityScore < 0 || severityScore > 100) {
      return res.status(400).json({ error: "severityScore is required and must be a number 0-100" });
    }

    if (SIMULATE) {
      const txHash = simAttest(indicatorHash, severityScore);
      console.log(`[SIM] attestIndicator: hash=${indicatorHash.slice(0, 16)}… score=${severityScore} tx=${txHash.slice(0, 18)}…`);
      return res.json({ txHash, status: "confirmed" });
    }

    if (!midnightContract) throw new Error("Midnight contract not initialized. Have you deployed it?");

    console.log(`[REAL] Sending attestIndicator for hash=${indicatorHash}`);
    const tx = await midnightContract.attestIndicator(indicatorHash, severityScore);
    return res.json({ txHash: tx.hash || tx.transactionId, status: "confirmed" });
  } catch (err) {
    console.error("[ERROR] /attest failed:", err.message);
    return res.status(500).json({ error: "Attestation failed", detail: err.message, status: "failed" });
  }
});

/**
 * GET /query/:hash
 * Response: { corroborationCount: number, highConfidenceCount: number }
 */
app.get("/query/:hash", async (req, res) => {
  try {
    const { hash } = req.params;

    if (SIMULATE) {
      const result = simQuery(hash);
      console.log(`[SIM] queryIndicator: hash=${hash.slice(0, 16)}… corroboration=${result.corroborationCount}`);
      return res.json(result);
    }

    if (!midnightContract) throw new Error("Midnight contract not initialized.");

    console.log(`[REAL] Querying queryIndicator for hash=${hash}`);
    const corroborationCount = await midnightContract.queryIndicator(hash);
    return res.json({
      corroborationCount: Number(corroborationCount),
      highConfidenceCount: 0 // Only exposed via direct state lookup in this implementation
    });
  } catch (err) {
    console.error("[ERROR] /query failed:", err.message);
    return res.status(500).json({ error: "Query failed", detail: err.message });
  }
});

/**
 * GET /stats
 * Response: { totalAttestations: number, uniqueIndicators: number, networkMode: string }
 */
app.get("/stats", async (req, res) => {
  try {
    if (SIMULATE) {
      return res.json({
        totalAttestations: simState.totalAttestations,
        uniqueIndicators: simState.corroborationCount.size,
        networkMode: "simulate",
      });
    }

    if (!midnightContract) throw new Error("Midnight contract not initialized.");
    const state = await midnightContract.state();
    
    return res.json({
      totalAttestations: Number(state.totalAttestations),
      uniqueIndicators: -1, // Maps don't easily export size in the JS binding
      networkMode: process.env.MIDNIGHT_NETWORK || "real",
    });
  } catch (err) {
    console.error("[ERROR] /stats failed:", err.message);
    return res.status(500).json({ error: "Stats query failed", detail: err.message });
  }
});

/**
 * GET /health
 */
app.get("/health", (req, res) => {
  res.json({
    status: "ok",
    service: "midnight-bridge",
    simulate: SIMULATE,
    network: process.env.MIDNIGHT_NETWORK || "local-devnet",
    contractAddress: process.env.MIDNIGHT_CONTRACT_ADDRESS || null,
    initialized: !!midnightContract
  });
});

// ─── Start ──────────────────────────────────────────────────────────────────

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`midnight-bridge listening on :${PORT} [simulate=${SIMULATE}]`);
  });
}

module.exports = app;
